data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: markusneighborlyapp
---
data:
  host.master: clFDdnhZczhLOWt3YTZmV2ZmYWRrMExaZ1gzUnZjMXE3bDhiUDhuWWJaRTZNVlQwZ0Q1WXV3PT0=
  host.function.default: cTVrNTVrblcweGJKdDhMbTZ5L3VWZ2xzdjljR3ZRYkViajZMQUxOczZBUEtveTFpTXl6YUFnPT0=
  host.systemKey.default: d3I2STZ6UHYwN2lsQlNGY0hFc1huWXBySWd0R1NmaTdSL2V4WmhDTk1zRGlhYWZvZWJtTmlnPT0=
  functions.createadvertisement.default: eG9oWjNCV1ZMR2NwYnJ6WElzUXVQQ2JlRUVSVDNxUEhHd0phOGxvaG4yQzFhMTFOcS9IOFlRPT0=
  functions.deleteadvertisement.default: anFuV0IxMUVyL2FCYU5jRllReUJTOUtHY1NVVm4yY2cwLzVRTkRpSEpKc2ZTMnc3TVFxMWpBPT0=
  functions.getadvertisement.default: TEpQMGJZUGtZQkhOYkJSSlBNV2Ixczh2V3d2WW9hay9sTGFWR0J1QzR5T3lvbDlyT2FLMGJ3PT0=
  functions.getadvertisements.default: dy9GR0hxNE5US2NEWUlMZjYzZXJ6Sy9ZVkV4czY5ckxmWE9pd1NUajJIeHdyTi85ajVFdi93PT0=
  functions.getpost.default: VFFoSWF5cEpiQU9pQld0V3dLS3oydlZ5TXo1b1VETFFOdE9xRWczNmF2SnNaaGpRdXFKc1NBPT0=
  functions.getposts.default: M0M4WGpXTlp2QVJiLzNNNlRxNmdHL3RZeGZ1cy91ZWJQazYxbTlkSndGQnRkWjB2N1ZPTUV3PT0=
  functions.updateadvertisement.default: bTgyUk1QZTZ4WVNvaGJ3WDRaMHlSaGgvdzE1a0Rxc1pmMXdHU1VKYzJZMnJ4T0ttcVdBYjZBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-markusneighborlyapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: markusneighborlyapp-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: markusneighborlyapp-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: markusneighborlyapp-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: markusneighborlyapp-http
spec:
  selector:
    app: markusneighborlyapp-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markusneighborlyapp-http
  labels:
    app: markusneighborlyapp-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markusneighborlyapp-http
  template:
    metadata:
      labels:
        app: markusneighborlyapp-http
    spec:
      containers:
      - name: markusneighborlyapp-http
        image: markusneighborlyapp.azurecr.io/markusneighborlyapp
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-markusneighborlyapp
        envFrom:
        - secretRef:
            name: markusneighborlyapp
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: markusneighborlyapp-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markusneighborlyapp
  labels:
    app: markusneighborlyapp
spec:
  selector:
    matchLabels:
      app: markusneighborlyapp
  template:
    metadata:
      labels:
        app: markusneighborlyapp
    spec:
      containers:
      - name: markusneighborlyapp
        image: markusneighborlyapp.azurecr.io/markusneighborlyapp
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: markusneighborlyapp
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: markusneighborlyapp-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: markusneighborlyapp
  labels: {}
spec:
  scaleTargetRef:
    name: markusneighborlyapp
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: neighborlyhub
      connection: Endpoint=sb://neighborlyhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=8rrArnsWnOFo3RRGiXNO86MzCyJ0BdPbpE7/nmYiXjg=
---

